export interface ServiceDetail {
  title: string;
  slug: string;
  shortDescription: string;
  fullDescription: string;
  metaDescription: string;
  features: string[];
  benefits: string[];
  useCases: string[];
  technologies: string[];
  process: string[];
}

export const servicesData: ServiceDetail[] = [
  {
    title: "Website Development",
    slug: "website-development",
    shortDescription:
      "Crafting responsive, high-performance websites tailored to your business needs, ensuring a seamless user experience across all devices.",
    fullDescription:
      "At Janixware, we specialize in creating modern, responsive websites that not only look stunning but also deliver exceptional performance and user experience. Our website development services encompass everything from simple business websites to complex web applications. We use cutting-edge technologies and best practices to ensure your website is fast, secure, scalable, and optimized for search engines. Our team works closely with you to understand your business goals, target audience, and brand identity to create a website that truly represents your business and drives results.",
    metaDescription:
      "Professional website development services by Janixware. We build responsive, high-performance websites tailored to your business needs. Modern web technologies, SEO optimization, and exceptional user experience.",
    features: [
      "Responsive design for all devices (mobile, tablet, desktop)",
      "SEO optimization for better search engine rankings",
      "Fast loading times and optimized performance",
      "Secure and scalable architecture",
      "Modern UI/UX design principles",
      "Content Management System (CMS) integration",
      "E-commerce functionality (if needed)",
      "Analytics and tracking integration",
    ],
    benefits: [
      "Increased online visibility and brand presence",
      "Enhanced user engagement and conversion rates",
      "Improved search engine rankings",
      "Mobile-friendly experience for all users",
      "Scalable solution that grows with your business",
      "Professional appearance that builds trust",
      "Easy content updates and maintenance",
      "Integration with existing business tools",
    ],
    useCases: [
      "Business websites and corporate portals",
      "E-commerce and online stores",
      "Portfolio and showcase websites",
      "Blog and content publishing platforms",
      "Landing pages for marketing campaigns",
      "Web applications and SaaS platforms",
      "Non-profit and community websites",
      "Educational institution websites",
    ],
    technologies: [
      "React",
      "Next.js",
      "Node.js",
      "TypeScript",
      "JavaScript",
      "HTML5",
      "CSS3",
      "Tailwind CSS",
      "PostgreSQL",
      "MongoDB",
      "AWS",
      "Google Cloud",
    ],
    process: [
      "Initial consultation and requirements gathering",
      "Planning and wireframing",
      "Design mockups and approval",
      "Development and coding",
      "Testing and quality assurance",
      "Content integration",
      "SEO optimization",
      "Deployment and launch",
      "Post-launch support and maintenance",
    ],
  },
  {
    title: "Landing Pages for Businesses",
    slug: "landing-pages",
    shortDescription:
      "Designing conversion-focused landing pages that effectively capture leads and drive action for your marketing campaigns.",
    fullDescription:
      "Landing pages are critical components of any successful digital marketing campaign. At Janixware, we create high-converting landing pages that are specifically designed to turn visitors into leads and customers. Our landing page development focuses on compelling copywriting, strategic design, and conversion optimization. We implement A/B testing, track performance metrics, and continuously optimize to maximize your conversion rates. Whether you're running paid ads, email campaigns, or social media promotions, our landing pages are crafted to align with your marketing objectives and drive measurable results.",
    metaDescription:
      "High-converting landing page development by Janixware. Conversion-focused design, A/B testing, and lead generation optimization for your marketing campaigns.",
    features: [
      "Conversion-optimized design and layout",
      "Mobile-responsive for all devices",
      "Fast loading speed for better conversions",
      "A/B testing capabilities",
      "Lead capture forms and integrations",
      "Social proof and testimonials",
      "Clear call-to-action buttons",
      "Analytics and conversion tracking",
    ],
    benefits: [
      "Higher conversion rates and lead generation",
      "Improved ROI on marketing campaigns",
      "Better targeting and personalization",
      "Reduced bounce rates",
      "Professional appearance builds trust",
      "Easy integration with marketing tools",
      "Scalable for multiple campaigns",
      "Data-driven optimization",
    ],
    useCases: [
      "Product launch campaigns",
      "Email marketing campaigns",
      "Social media advertising",
      "Pay-per-click (PPC) campaigns",
      "Webinar registrations",
      "Free trial sign-ups",
      "Lead magnets and downloads",
      "Event registrations",
    ],
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "HTML5",
      "CSS3",
      "JavaScript",
      "Google Analytics",
      "Conversion tracking tools",
    ],
    process: [
      "Campaign goal analysis",
      "Target audience research",
      "Wireframing and design mockups",
      "Copywriting and content creation",
      "Development and coding",
      "Form and integration setup",
      "Testing and optimization",
      "Launch and monitoring",
      "A/B testing and iteration",
    ],
  },
  {
    title: "Custom Software Solutions",
    slug: "custom-software",
    shortDescription:
      "Developing bespoke software applications that streamline operations, automate tasks, and solve unique business challenges.",
    fullDescription:
      "Every business has unique needs and challenges that off-the-shelf software often can't address. At Janixware, we develop custom software solutions that are tailored specifically to your business processes and requirements. Our custom software development approach involves deep understanding of your workflows, pain points, and objectives. We build scalable, maintainable, and secure applications that integrate seamlessly with your existing systems. From desktop applications to complex enterprise solutions, we deliver software that empowers your team, improves efficiency, and drives business growth.",
    metaDescription:
      "Custom software development services by Janixware. Bespoke applications tailored to your business needs, automating workflows and solving unique challenges.",
    features: [
      "Tailored to your specific business needs",
      "Scalable architecture for future growth",
      "Integration with existing systems",
      "User-friendly interface design",
      "Secure and compliant development",
      "Comprehensive documentation",
      "Training and support",
      "Ongoing maintenance and updates",
    ],
    benefits: [
      "Increased operational efficiency",
      "Automated workflows and processes",
      "Better data management and insights",
      "Reduced manual errors",
      "Competitive advantage",
      "Cost savings over time",
      "Improved decision-making",
      "Streamlined business operations",
    ],
    useCases: [
      "Business process automation",
      "Inventory management systems",
      "Customer relationship management (CRM)",
      "Enterprise resource planning (ERP)",
      "Project management tools",
      "Reporting and analytics dashboards",
      "Workflow automation",
      "Custom business applications",
    ],
    technologies: [
      "Python",
      "Java",
      "Node.js",
      "React",
      "Next.js",
      "PostgreSQL",
      "MongoDB",
      "MySQL",
      "AWS",
      "Azure",
      "Docker",
      "Kubernetes",
    ],
    process: [
      "Requirements analysis and documentation",
      "System architecture design",
      "Database design and planning",
      "Development sprints and iterations",
      "Quality assurance and testing",
      "User acceptance testing (UAT)",
      "Deployment and migration",
      "Training and knowledge transfer",
      "Ongoing support and maintenance",
    ],
  },
  {
    title: "System Automation",
    slug: "system-automation",
    shortDescription:
      "Implementing intelligent automation solutions to enhance efficiency, reduce manual effort, and optimize your workflows.",
    fullDescription:
      "In today's fast-paced business environment, automation is key to staying competitive. Janixware helps businesses automate repetitive tasks, streamline workflows, and eliminate manual processes through intelligent automation solutions. We analyze your current processes, identify automation opportunities, and implement solutions that save time, reduce errors, and increase productivity. From simple task automation to complex workflow orchestration, our automation solutions integrate seamlessly with your existing systems and scale as your business grows.",
    metaDescription:
      "Business process automation services by Janixware. Intelligent automation solutions to streamline workflows, reduce manual effort, and enhance operational efficiency.",
    features: [
      "Workflow automation and orchestration",
      "Task scheduling and execution",
      "Integration with multiple systems",
      "Error handling and notifications",
      "Monitoring and logging",
      "Scalable architecture",
      "API integrations",
      "Custom automation scripts",
    ],
    benefits: [
      "Significant time savings",
      "Reduced manual errors",
      "Improved productivity",
      "Cost reduction",
      "24/7 automated execution",
      "Better resource utilization",
      "Enhanced data accuracy",
      "Faster processing times",
    ],
    useCases: [
      "Data entry automation",
      "Email automation",
      "Report generation",
      "Backup and synchronization",
      "Order processing automation",
      "Customer onboarding workflows",
      "Invoice processing",
      "Inventory management automation",
    ],
    technologies: [
      "Python",
      "Node.js",
      "JavaScript",
      "Java",
      "Go",
      "API integrations",
      "RPA tools",
      "Workflow engines",
      "AWS Lambda",
      "Google Cloud Functions",
    ],
    process: [
      "Process analysis and mapping",
      "Automation opportunity identification",
      "Solution design and architecture",
      "Development and implementation",
      "Integration with existing systems",
      "Testing and validation",
      "Deployment and monitoring",
      "Documentation and training",
      "Ongoing optimization",
    ],
  },
  {
    title: "API Development",
    slug: "api-development",
    shortDescription:
      "Building robust and secure APIs that enable seamless integration between your applications and third-party services.",
    fullDescription:
      "APIs are the backbone of modern software architecture, enabling applications to communicate and share data efficiently. At Janixware, we develop robust, secure, and scalable RESTful APIs and GraphQL APIs that power your applications and enable seamless integrations. Our API development follows industry best practices for security, performance, and documentation. We build APIs that are easy to consume, well-documented, version-controlled, and designed for scale. Whether you need internal APIs for microservices architecture or public APIs for partner integrations, we deliver solutions that meet your requirements.",
    metaDescription:
      "Professional API development services by Janixware. Building secure, scalable REST and GraphQL APIs for seamless application integration and third-party services.",
    features: [
      "RESTful and GraphQL API design",
      "Comprehensive API documentation",
      "Authentication and authorization",
      "Rate limiting and throttling",
      "Error handling and validation",
      "Version control and management",
      "API testing and monitoring",
      "Security best practices",
    ],
    benefits: [
      "Seamless system integration",
      "Improved data accessibility",
      "Enhanced application scalability",
      "Better partner collaboration",
      "Reduced development time",
      "Standardized data exchange",
      "Easier maintenance",
      "Future-proof architecture",
    ],
    useCases: [
      "Microservices architecture",
      "Third-party service integration",
      "Mobile app backend APIs",
      "Partner API development",
      "Data synchronization",
      "Payment gateway integration",
      "Social media integrations",
      "Cloud service integrations",
    ],
    technologies: [
      "Node.js",
      "Python",
      "Java",
      "Spring Boot",
      "Express.js",
      "FastAPI",
      "GraphQL",
      "PostgreSQL",
      "MongoDB",
      "Redis",
      "AWS API Gateway",
      "Docker",
    ],
    process: [
      "API requirements analysis",
      "Architecture and design",
      "Database schema design",
      "Development and coding",
      "Authentication implementation",
      "Testing and validation",
      "Documentation creation",
      "Security audit",
      "Deployment and monitoring",
    ],
  },
  {
    title: "Mobile App Development",
    slug: "mobile-app-development",
    shortDescription:
      "Creating intuitive and feature-rich native or cross-platform mobile applications for iOS and Android, bringing your ideas to users' fingertips.",
    fullDescription:
      "Mobile applications have become essential for businesses to reach and engage with their customers. Janixware develops high-quality mobile applications for both iOS and Android platforms using native and cross-platform technologies. Our mobile app development services cover the entire lifecycle from ideation and design to development, testing, and deployment. We create apps that deliver excellent user experience, high performance, and seamless functionality. Whether you need a native app for optimal performance or a cross-platform solution for faster development and deployment, we have the expertise to bring your mobile app vision to life.",
    metaDescription:
      "Mobile app development services by Janixware. Native and cross-platform iOS and Android applications with excellent UX, performance, and seamless functionality.",
    features: [
      "Native iOS and Android development",
      "Cross-platform development (React Native)",
      "Intuitive UI/UX design",
      "Push notifications",
      "Offline functionality",
      "App store optimization",
      "Performance optimization",
      "Security and data encryption",
    ],
    benefits: [
      "Increased customer engagement",
      "Improved brand visibility",
      "Direct customer communication channel",
      "Enhanced user experience",
      "Revenue generation opportunities",
      "Competitive advantage",
      "Customer loyalty",
      "Data collection and insights",
    ],
    useCases: [
      "Customer-facing mobile apps",
      "E-commerce mobile applications",
      "Social media applications",
      "Fitness and health apps",
      "Productivity and business apps",
      "Gaming applications",
      "Educational apps",
      "On-demand service apps",
    ],
    technologies: [
      "React Native",
      "Flutter",
      "Swift (iOS)",
      "Kotlin (Android)",
      "JavaScript",
      "TypeScript",
      "Node.js",
      "Firebase",
      "AWS",
      "Google Cloud",
      "MongoDB",
      "PostgreSQL",
    ],
    process: [
      "Concept and ideation",
      "UI/UX design and prototyping",
      "Technical architecture",
      "Development sprints",
      "Testing and QA",
      "App store preparation",
      "Beta testing",
      "Launch and deployment",
      "Post-launch support and updates",
    ],
  },
];

export function getServiceBySlug(slug: string): ServiceDetail | undefined {
  return servicesData.find((service) => service.slug === slug);
}

export function getAllServiceSlugs(): string[] {
  return servicesData.map((service) => service.slug);
}

